function myBirthYearFunc(){
    console.log("Nací en " + 1980);
}
//el año en el que nacio o el que puso



function myBirthYearFunc(EntradaAñoNacimiento){
    console.log("Nací en " + EntradaAñoNacimiento);
}
//Naci en 1980 



function add(num1, num2){
    console.log("¡Sumando números!");
    console.log("num1 is: " + num1);
    console.log("num2 is: " + num2);
    var sum = num1 + num2;
    console.log(sum);
}
//resultado =30